-- Schema for Supabase PostgreSQL listings table
CREATE TABLE IF NOT EXISTS listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_url TEXT UNIQUE NOT NULL,
    title TEXT,
    model_name TEXT,
    asking_price NUMERIC(10, 2),
    market_value NUMERIC(10, 2),
    profit_margin NUMERIC(10, 2),
    is_profitable_deal BOOLEAN DEFAULT FALSE NOT NULL,
    confidence_score NUMERIC(5, 4),
    damage_severity TEXT DEFAULT 'none' NOT NULL,
    damage_notes TEXT,
    image_urls JSONB DEFAULT '[]'::jsonb NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE listings DISABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_listings_is_profitable ON listings (is_profitable_deal);
CREATE INDEX IF NOT EXISTS idx_listings_model_name ON listings (model_name);
CREATE INDEX IF NOT EXISTS idx_listings_created_at ON listings (created_at DESC);
